### ISSUE TITLE
Performance issue in heavily saturated usage

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/OpenSSL.jl#16]
It's unclear whether there is something fundamental in OpenSSL.jl or HTTP.jl's usage of it, but we noticed in a RelationalAI workload that executed thousands of concurrent requests (GET, PUT, etc.) to cloud storage that there was slowdown in these heavily saturated scenarios.

**Comment by grlap** [comment]
Any chance of getting and sharing profile data ?

**Comment by quinnj** [comment]
I don't; we have an extremely large/complicated benchmark that involves a 128-node cluster doing thousands of cloud storage requests where we noticed the slowdown. I'm hoping to have time to work on this in the next month or two.

**Comment by quinnj** [comment]
Resolved by https://github.com/JuliaWeb/OpenSSL.jl/pull/20
